CREATE TABLE IF NOT EXISTS `Consultas_SQL_BigQuery_Projeto_2_Laboratoria` (
    `Consultas_SQL_BigQuery_Projeto_02_Laboratoria` VARCHAR(180) CHARACTER SET utf8,
    `Column_2` VARCHAR(67) CHARACTER SET utf8,
    `Column_3` VARCHAR(42) CHARACTER SET utf8,
    `Column_4` VARCHAR(12) CHARACTER SET utf8,
    `Column_5` VARCHAR(35) CHARACTER SET utf8,
    `Column_6` VARCHAR(4) CHARACTER SET utf8,
    `Column_7` VARCHAR(34) CHARACTER SET utf8,
    `Column_8` INT,
    `Column_9` VARCHAR(29) CHARACTER SET utf8,
    `Column_10` INT
);
INSERT INTO `Consultas_SQL_BigQuery_Projeto_2_Laboratoria` VALUES ('--Testando Hipóteses - Spotify',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('//Identificando e tratando valores nulos',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('SELECT',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('COUNTIF(track_id IS NULL) AS nulls_track_id',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('COUNTIF(in_apple_playlists IS NULL) AS nulls_apple_playlists',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('COUNTIF(in_apple_charts IS NULL) AS nulls_apple_charts',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('COUNTIF(in_deezer_playlists IS NULL) AS nulls_deezer_playlists',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('COUNTIF(in_deezer_charts IS NULL) AS nulls_deezer_charts',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('COUNTIF(in_shazam_charts IS NULL) AS nulls_shazam_charts',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('FROM `hipoteses-spotify.projeto002.track_in_competition`',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('CREATE OR REPLACE TABLE `hipoteses-spotify.projeto002.track_in_spotify_clean` AS',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('SELECT * FROM `hipoteses-spotify.projeto002.track_in_spotify_clean` WHERE streams IS NOT NULL',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('--track_technical_info',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('SELECT',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('COUNTIF(track_id IS NULL) AS nulls_track_id',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('COUNTIF(bpm IS NULL) AS nulls_bpm',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('COUNTIF(key IS NULL) AS nulls_key',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('COUNTIF(mode IS NULL) AS nulls_mode',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('COUNTIF(danceability__ IS NULL) AS nulls_dance',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('COUNTIF(valence__ IS NULL) AS nulls_valence',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('COUNTIF(energy__ IS NULL) AS nulls_energy',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('COUNTIF(acousticness__ IS NULL) AS nulls_acoustic',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('COUNTIF(instrumentalness__ IS NULL) AS nulls_instrumental',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('COUNTIF(liveness__ IS NULL) AS nulls_live',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('COUNTIF(speechiness__ IS NULL) AS nulls_speechi',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('FROM `hipoteses-spotify.projeto002.track_technical_info`',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('--track_in_spotify',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('SELECT',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('COUNTIF(track_id IS NULL) AS nulls_in_column1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('COUNTIF(track_name IS NULL) AS nulls_in_column2',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('COUNTIF(artist_s__name IS NULL) AS nulls_in_column3',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('COUNTIF(artist_count IS NULL) AS nulls_in_column4',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('COUNTIF(released_year IS NULL) AS nulls_in_column5',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('COUNTIF(released_month IS NULL) AS nulls_in_column6',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('COUNTIF(released_day IS NULL) AS nulls_in_column7',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('COUNTIF(in_spotify_playlists IS NULL) AS nulls_in_column8',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('COUNTIF(in_spotify_charts IS NULL) AS nulls_in_column9',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('COUNTIF(streams IS NULL) AS nulls_in_column10',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('FROM `hipoteses-spotify.projeto002.track_in_spotify`',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('//Identificando e Tratando Valores Duplicados',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('--track_in_competition',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('SELECT track_id',' COUNT(*)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('FROM `hipoteses-spotify.projeto002.track_in_spotify`',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('GROUP BY track_id ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('HAVING COUNT(*) > 1;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('--track_in_spotify',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('--track_name',' artist(s)_name (colunas com dup)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('SELECT track_name',' artist_s__name',' COUNT(*)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('FROM `hipoteses-spotify.projeto002.track_in_spotify`',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('GROUP BY track_name',' artist_s__name',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('HAVING COUNT(*) > 1;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('--track_technical_info',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('SELECT track_id',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('COUNT(*)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('FROM `hipoteses-spotify.projeto002.track_technical_info`',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('GROUP BY track_id ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('HAVING COUNT(*) > 1;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('CREATE OR REPLACE TABLE hipoteses-spotify.projeto002.track_in_spotify_clean2_semdup ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('AS SELECT  track_id','  ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('track_name','  ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('artist_s__name','  ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('artist_count',' ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('released_year','  ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('released_month','  ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('released_day','  ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('in_spotify_playlists','  ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('in_spotify_charts','  ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('streams',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('FROM hipoteses-spotify.projeto002.track_in_spotify_clean2 WHERE track_id NOT IN (''8173823''',' ''1119309''',' ''7173596''',' ''3814670'');',NULL,NULL,NULL,NULL,NULL,NULL),
	(NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('//Identificando e tratando dados fora do escopo de análise',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('--track_technical_info',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('SELECT * EXCEPT (key',' mode) --todas as demais colunas serão exibidas com exceção a essas',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('FROM `hipoteses-spotify.projeto002.track_technical_info` ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('--track_in_competition',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('SELECT * EXCEPT (in_shazam_charts)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('FROM `hipoteses-spotify.projeto002.track_in_competition` ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('//Identificando e tratando dados discrepantes em variáveis categóricas',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('--remover caracteres especiais de uma string ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('--tabelas que tem carac. especiais: track_in_spotify - spotify',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('--verificar e alterar tipo de dados',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('SELECT ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('track_id',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('LOWER(REGEXP_REPLACE(track_name',' r''[^\\w]+''',' '' '')) AS track_name',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('LOWER(REGEXP_REPLACE(artist_s__name',' r''[^\\w]+''',' '' '')) AS artist_s__name',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('artist_count',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('released_year',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('released_month',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('released_day',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('in_spotify_playlists',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('in_spotify_charts',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('SAFE_CAST(streams AS INT64) AS streams',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('FROM `hipoteses-spotify.projeto002.track_in_spotify`',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('//Observando Valores Máx/Mín/Média em variáveis numéricas',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('--track_in_spotify',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('SELECT',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    MAX(released_year) AS max_released_year',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    MIN(released_year) AS min_released_year',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    AVG(released_year) AS avg_released_year',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    MAX(released_month) AS max_released_month',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    MIN(released_month) AS min_released_month',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    AVG(released_month) AS avg_released_month',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    MAX(released_day) AS max_released_day',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    MIN(released_day) AS min_released_day',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    AVG(released_day) AS avg_released_day',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    MAX(in_spotify_playlists) AS max_in_spotify_playlists',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    MIN(in_spotify_playlists) AS min_in_spotify_playlists',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    AVG(in_spotify_playlists) AS avg_in_spotify_playlists',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    MAX(in_spotify_charts) AS max_in_spotify_charts',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    MIN(in_spotify_charts) AS min_in_spotify_charts',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    AVG(in_spotify_charts) AS avg_in_spotify_charts',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('   FROM `hipoteses-spotify.projeto002.track_in_spotify`',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('   ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('--track_technical_info',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('SELECT',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    MAX(bpm) AS max_bpm',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    MIN(bpm) AS min_bpm',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    AVG(bpm) AS avg_bpm',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    MAX(danceability__) AS max_danceability__',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    MIN(danceability__) AS min_danceability__',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    AVG(danceability__) AS avg_danceability__',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    MAX(valence__) AS max_valence__',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    MIN(valence__) AS min_valence__',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    AVG(valence__) AS avg_valence__',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    MAX(energy__) AS max_energy__',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    MIN(energy__) AS min_energy__',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    AVG(energy__) AS avg_energy__',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    MAX(acousticness__) AS max_acousticness__',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    MIN(acousticness__) AS min_acousticness__',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    AVG(acousticness__) AS avg_acousticness__',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    MAX(instrumentalness__) AS max_instrumentalness__',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    MIN(instrumentalness__) AS min_instrumentalness__',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    AVG(instrumentalness__) AS avg_instrumentalness__',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    MAX(liveness__) AS max_liveness__',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    MIN(liveness__) AS min_liveness__',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    AVG(liveness__) AS avg_liveness__',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    MAX(speechiness__) AS max_speechiness__',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    MIN(speechiness__) AS min_speechiness__',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    AVG(speechiness__) AS avg_speechiness__',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('   FROM `hipoteses-spotify.projeto002.track_technical_info_clean`',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('   ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('   --track_in_competion',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('   SELECT',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    MAX(in_apple_playlists) AS max_in_apple_playlists',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    MIN(in_apple_playlists) AS min_in_apple_playlists',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    AVG(in_apple_playlists) AS avg_in_apple_playlists',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    MAX(in_apple_charts) AS max_in_apple_charts',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    MIN(in_apple_charts) AS min_in_apple_charts',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    AVG(in_apple_charts) AS avg_in_apple_charts',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    MAX(in_deezer_playlists) AS max_in_deezer_playlists',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    MIN(in_deezer_playlists) AS min_in_deezer_playlists',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    AVG(in_deezer_playlists) AS avg_in_deezer_playlists',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    MAX(in_deezer_charts) AS max_in_deezer_charts',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    MIN(in_deezer_charts) AS min_in_deezer_charts',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    AVG(in_deezer_charts) AS avg_in_deezer_charts',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    FROM `hipoteses-spotify.projeto002.track_in_competion_clean`',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('//Identificando data errônea e substituindo',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('CREATE OR REPLACE TABLE `hipoteses-spotify.projeto002.track_in_spotify_clean` AS',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('SELECT',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  track_id',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  track_name',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  artist_s__name',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  artist_count',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  CASE WHEN track_id = ''2475712'' THEN 2022 ELSE CAST(released_year AS INT64) END AS released_year',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  CASE WHEN track_id = ''2475712'' THEN 10 ELSE CAST(released_month AS INT64) END AS released_month',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  CASE WHEN track_id = ''2475712'' THEN 10 ELSE CAST(released_day AS INT64) END AS released_day',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  in_spotify_playlists',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  in_spotify_charts',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  streams',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('FROM `hipoteses-spotify.projeto002.track_in_spotify_clean`;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('//Retirando Nulo na Variável Streams',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('CREATE OR REPLACE TABLE `hipoteses-spotify.projeto002.track_in_spotify_clean` AS SELECT * FROM `hipoteses-spotify.projeto002.track_in_spotify_clean` WHERE streams_clean IS NOT NULL',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('//Criando variáveis de Data',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('CREATE OR REPLACE TABLE `hipoteses-spotify.projeto002.track_in_spotify_clean` AS',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('SELECT',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  track_id',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  track_name',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  artist_s__name',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  artist_count',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('released_year',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('released_month',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('released_day',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  CONCAT(CAST(released_year AS STRING)',' ''-''',' LPAD(CAST(released_month AS STRING)',' 2',' ''0'')',' ''-''',' LPAD(CAST(released_day AS STRING)', 2,' ''0'')) AS release_date_concat',NULL),
	('  CONCAT(CAST(released_year AS STRING)',' ''-''',' LPAD(CAST(released_month AS STRING)',' 2',' ''0'')) AS release_year_month_concat',NULL,NULL,NULL,NULL,NULL),
	('  in_spotify_playlists',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  in_spotify_charts',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  streams',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('FROM `hipoteses-spotify.projeto002.track_in_spotify_clean`;CREATE OR REPLACE TABLE `hipoteses-spotify.projeto002.track_in_spotify_clean` AS',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('SELECT',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  track_id',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  track_name',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  artist_s__name',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  artist_count',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('released_year',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('released_month',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('released_day',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  CONCAT(CAST(released_year AS STRING)',' ''-''',' LPAD(CAST(released_month AS STRING)',' 2',' ''0'')',' ''-''',' LPAD(CAST(released_day AS STRING)', 2,' ''0'')) AS release_date_concat',NULL),
	('  CONCAT(CAST(released_year AS STRING)',' ''-''',' LPAD(CAST(released_month AS STRING)',' 2',' ''0'')) AS release_year_month_concat',NULL,NULL,NULL,NULL,NULL),
	('  in_spotify_playlists',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  in_spotify_charts',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  streams',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('FROM `hipoteses-spotify.projeto002.track_in_spotify_clean`;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('//Unindo tabelas',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('SELECT *',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('FROM hipoteses-spotify.projeto002.track_in_spotify_clean AS tp',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('LEFT JOIN hipoteses-spotify.projeto002.track_in_competion_clean AS ts',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('ON tp.track_id = ts.track_id',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('LEFT JOIN hipoteses-spotify.projeto002.track_technical_info_clean AS tt',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('ON tp.track_id = tt.track_id;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('//Construindo tabelas auxiliares',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('--total de músicas de artistas solo artista (só artista solo)',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('WITH musicas_por_artista AS (',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  SELECT',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    artist_s__name',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    COUNT(*) AS total_musicas',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  FROM `hipoteses-spotify.projeto002.full_table_spotify`',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  WHERE artist_count = 1  -- Filtra apenas os artistas solo',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  GROUP BY artist_s__name',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(')',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('SELECT * FROM musicas_por_artista;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('//Incluindo "não identificado" em track_name que ficaram sem nome na música após remoção de caracteres especiais',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('CREATE OR REPLACE TABLE `hipoteses-spotify.projeto002.full_table_spotify` AS',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('SELECT',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('track_id',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('CASE WHEN track_id = ''6720570'' THEN ''nao identificado'' ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('WHEN track_id =  ''5865058'' THEN ''nao identificado'' ELSE CAST (track_name AS STRING) END AS track_name',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('      artist_s__name',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    artist_count',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    released_year',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    released_month',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    released_day',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    release_date_concat',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    release_year_month_concat',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    in_spotify_playlists',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `Consultas_SQL_BigQuery_Projeto_2_Laboratoria` VALUES ('    in_spotify_charts',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    streams',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    in_apple_playlists',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    in_apple_charts',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    in_deezer_playlists',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    in_deezer_charts',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    bpm',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    danceability__',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    valence__',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    energy__',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    acousticness__',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    instrumentalness__',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    liveness__',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    speechiness__',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('FROM',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    `hipoteses-spotify.projeto002.full_table_spotify`',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('//Dividindo Variáveis em Quartis e Recategorizando',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('WITH quartis AS (',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  SELECT',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    track_id',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    bpm',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    NTILE(4) OVER (ORDER BY bpm) AS bpm_quartil',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    danceability__',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    NTILE(4) OVER (ORDER BY danceability__) AS danceability_quartil',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    valence__',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    NTILE(4) OVER (ORDER BY valence__) AS valence_quartil',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    energy__',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    NTILE(4) OVER (ORDER BY energy__) AS energy_quartil',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    acousticness__',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    NTILE(4) OVER (ORDER BY acousticness__) AS acousticness_quartil',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    instrumentalness__',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    NTILE(4) OVER (ORDER BY instrumentalness__) AS instrumentalness_quartil',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    liveness__',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    NTILE(4) OVER (ORDER BY liveness__) AS liveness_quartil',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    speechiness__',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    NTILE(4) OVER (ORDER BY speechiness__) AS speechiness_quartil',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  FROM',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('    `hipoteses-spotify.projeto002.full_table_spotify`',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(')',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('SELECT',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  a.*',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  q.bpm_quartil',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  IF(q.bpm_quartil=4',' "Alto"',' "Baixo") AS bpm_categorizada',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  q.danceability_quartil',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  IF (q.danceability_quartil=4',' "Alto"',' "Baixo") AS danceability_categorizada',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  q.valence_quartil',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  IF (valence_quartil=4',' "Alto"',' "Baixo") AS valence_categorizada',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  q.energy_quartil',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  IF (energy_quartil=4',' "Alto"',' "Baixo") AS energy_categorizada',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  q.acousticness_quartil',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  IF (acousticness_quartil=4',' "Alto"',' "Baixo") AS acousticness_categorizada',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  q.instrumentalness_quartil',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  IF (instrumentalness_quartil=4',' "Alto"',' "Baixo") AS instrumentalness_categorizada',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  q.liveness_quartil',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  IF (liveness_quartil=4',' "Alto"',' "Baixo") AS liveness_categorizada',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  q.speechiness_quartil',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  IF (speechiness_quartil=4',' "Alto"',' "Baixo") AS speechiness_categorizada',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('FROM ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(' `hipoteses-spotify.projeto002.full_table_spotify` a',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('JOIN ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  quartis q ON a.track_id = q.track_id',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('//Criando a variável Total em Playlists',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('CREATE OR REPLACE TABLE `hipoteses-spotify-419718.projeto002.full_table_spotify_quartis_total_playlists` AS',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('SELECT ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  track_id',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  track_name',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  artist_s__name',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  artist_count',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  released_year',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  released_month',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  released_day',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  release_date_concat',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  release_year_month_concat',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  SUM(in_spotify_playlists + in_apple_playlists + in_deezer_playlists) AS total_playlists',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  in_spotify_playlists',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  in_spotify_charts',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  streams',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  in_apple_playlists',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  in_apple_charts',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  in_deezer_playlists',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  in_deezer_charts',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  bpm',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  danceability__',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  valence__',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  energy__',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  acousticness__',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  instrumentalness__',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  liveness__',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  speechiness__',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  bpm_quartil',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  bpm_categorizada',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  danceability_quartil',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  danceability_categorizada',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  valence_quartil',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  valence_categorizada',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  energy_quartil',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  energy_categorizada',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  acousticness_quartil',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  acousticness_categorizada',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  instrumentalness_quartil',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  instrumentalness_categorizada',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  liveness_quartil',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  liveness_categorizada',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  speechiness_quartil',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  speechiness_categorizada',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('FROM ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  `hipoteses-spotify-419718.projeto002.full_table_spotify_quartis_segmento`',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('GROUP BY',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  track_id',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  track_name',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  artist_s__name',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  artist_count',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  released_year',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  released_month',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  released_day',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  release_date_concat',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  release_year_month_concat',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  in_spotify_playlists',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  in_spotify_charts',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  streams',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  in_apple_playlists',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  in_apple_charts',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  in_deezer_playlists',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  in_deezer_charts',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  bpm',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  danceability__',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  valence__',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  energy__',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  acousticness__',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  instrumentalness__',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  liveness__',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  speechiness__',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  bpm_quartil',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  bpm_categorizada',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  danceability_quartil',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  danceability_categorizada',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  valence_quartil',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  valence_categorizada',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  energy_quartil',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  energy_categorizada',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  acousticness_quartil',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  acousticness_categorizada',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  instrumentalness_quartil',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  instrumentalness_categorizada',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  liveness_quartil',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  liveness_categorizada',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  speechiness_quartil',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  speechiness_categorizada;',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('//Calculando correlação entre variáveis numéricas com o R de Pearson',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('SELECT',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('CORR (streams',' total_playlists) AS streams_totalplay_corr',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('CORR (streams',' in_spotify_playlists) AS streams_spotifyplay_corr',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('CORR (streams',' danceability__) AS streams_dance_corr',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('CORR (streams',' in_apple_playlists) AS streams_appleplay_corr',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('CORR (streams',' in_deezer_playlists) AS streams_deezerplay_corr',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('CORR (streams',' valence__) AS streams_valence_corr',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('CORR (streams',' energy__) AS steams_energy_corr',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('CORR (streams',' acousticness__) AS streams_acousticness_corr',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('CORR (streams',' instrumentalness__) AS streams_instrumentalness_corr',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('CORR (streams','liveness__) AS streams_liveness_corr',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('CORR (streams',' speechiness__) AS streams_speechiness_corr',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('CORR (streams',' bpm) AS streams_bpm_corr',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('FROM `hipoteses-spotify.projeto002.full_table_spotify` ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('//Criando tabela com quantidade de músicas por artistas e total de streams',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('CREATE TABLE `hipoteses-spotify.projeto002.artists-count-streams`',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('AS',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('SELECT',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  artist_s__name',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  COUNT(DISTINCT track_name) AS total_musicas',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('  SUM(streams) AS total_streams',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('FROM',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(' `hipoteses-spotify.projeto002.full_table_spotify`',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	('GROUP BY',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
	(' artist_s__name',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
